platform :ios, '10.0'
 
inhibit_all_warnings!
use_frameworks!
 
target 'quanTech' do
  pod 'Alamofire', '~> 4.2.0'
  pod "SwiftyXMLParser", :git => 'https://github.com/yahoojapan/SwiftyXMLParser.git'
end

